### ISSUE TITLE
UI/UX 개선하기

### ISSUE THREAD

**Issue by jaeyeong815** [jaeyeong815/wanted-pre-onboarding-fe-7#7]
#1 에서 제안했던 UI/UX 개선하기 부분 상세 리스트입니다.

### 시작 전 기능 분리

- [x] Todo 컴포넌트 기능별로 분리
	- [x] 전역 데이터로 todo 상태 관리하기

### UX

**Todo**

- [x] 할 일 등록 시 등록 완료 안내
- [x] 할 일 등록 오류 발생 시 안내 (ex. 빈칸으로 할 일 등록 -> 입력해달라고 안내)
- [x] 할 일 삭제, 수정 시 삭제, 수정 확인 안내

**Auth**

- [x] 로그인 시 로그인 완료 안내
- [x] 회원가입/로그인 오류 발생 시 안내
- [x] 로그아웃 기능 추가

### UI

<img width="387" alt="image" src="https://user-images.githubusercontent.com/85178602/214490642-defa9050-2936-4fb2-95b6-ca77525a2e08.png">

- [x] 투두 리스트 아이템들 사이 간격 늘리기
- [x] 투두 리스트 완료여부/내용/버튼 등 가로 간격 맞추기

**Comment by jaeyeong815** [comment]
모든 기능 구현 완료
